version: 22
jobs:
- name: Upload to git's
  steps:
  - !PushRepository
    name: Sync Main (GitHub)
    remoteUrl: https://github.com/MushroomSquad/Juliet
    userName: Don_Sudak
    passwordSecret: github
    force: false
    condition: ALWAYS
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
